#!/bin/bash
#
# downloads content from .m3u8 files

# ask for input file
# default to index.m3u8
[ -f index.m3u8 ] && m3u8=index.m3u8 || {
    printf ".m3u8 file to fetch: "
    read m3u8

    [ ! -f "$m3u8" ] && {
        echo "file not found"
        exit 1
    }
}

# make intermediate directory
[ ! -d .niffler ] && mkdir .niffler

# download each .ts segment
z=1
IFS=
while read -r line; do
    if [[ $line =~ ^(http.*)$ ]]; then
        curl -# -L $line --output .niffler/$z.ts --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
    ((z++))
    fi
done < $m3u8

# concatenate into a single file
i=1
while [ $i -lt $z ]; do
    [ $i -eq 1 ] && cp .niffler/$i.ts .niffler/video.ts || cat .niffler/$i.ts >> .niffler/video.ts
    ((i++))
done

# convert to .mp4 format
ffmpeg -i .niffler/video.ts -c:v copy -c:a copy niffler_video.mp4
