#!/bin/bash

main() {
    if [ -f "$HOME/Pictures/wallpaper/$1" ]; then
        # feh --bg-fill "$HOME/Pictures/wallpaper/$1"
        wal -i "$HOME/Pictures/wallpaper/$1"
    elif [ -f "$HOME/Pictures/wallpaper/${1}.jpg" ]; then
        # feh --bg-fill "$HOME/Pictures/wallpaper/${1}.jpg"
        wal -i "$HOME/Pictures/wallpaper/${1}.jpg"
    elif [ -f "$HOME/Pictures/wallpaper/${1}.jpeg" ]; then
        # feh --bg-fill "$HOME/Pictures/wallpaper/${1}.jpeg"
        wal -i "$HOME/Pictures/wallpaper/${1}.jpeg"
    elif [ -f "$HOME/Pictures/wallpaper/${1}.png" ]; then
        # feh --bg-fill "$HOME/Pictures/wallpaper/${1}.png"
        wal -i "$HOME/Pictures/wallpaper/${1}.png"
    else
        trap "stty icanon echo; printf '\033[?25h\033[2J\033[H'; exit 0" EXIT INT
        stty -icanon -echo

        cursor=0

        render

        while key=$(dd ibs=1 count=1 2>/dev/null); do
            if [ -n $escape ]; then
                case $key in
                    A)
                        down
                    ;;

                    B)
                        up
                    ;;
                esac

                unset escape
            fi

            [ "$key" == "[" ] && escape=true

            case $key in
                k)
                    down
                ;;

                j)
                    up
                ;;

                " "|"")
                    wal -q -i "${pictures[$cursor]}"
                    exit 0
                ;;

                q)
                    exit 0
                ;;
            esac

            render
        done
    fi
}

up() {
    [ $cursor -lt $((${#pictures[@]} - 1)) ] && ((cursor++))
}

down() {
    [ $cursor -ne 0 ] && ((cursor--))
}

render() {
    printf '\033[2J\033[H\033[?25l'

    pictures=()

    for file in $HOME/Pictures/wallpaper/*; do
        pictures+=("$file")

        file=${file%${file##*[!/]}}
        file=${file##*/}
        file=${file%.png}
        file=${file%.jpg}
        file=${file%.jpeg}

        if [[ "${pictures[$cursor]}" =~ "$file" ]]; then
            printf '\033[1m\033[44m\033[30m%s\033[m\n' $file
        else
            printf '\033[1m%s\033[m\n' $file
        fi
    done
}

main "$@"
