#!/bin/sh

[ ! -f ~/.cache/wal/colors ] && exit

set --

while read -r line; do
    set -- "$@" "$line"
done < ~/.cache/wal/colors

ratpoison -c "set bgcolor $1"
ratpoison -c "set fgcolor $2"

exit 0
